apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: nncp-workers-bond0-vlan2121
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ''
  desiredState:
    interfaces:
    - name: bond0.2121
      description: VLAN 2121 using bond0
      type: vlan
      state: up
      vlan:
        base-iface: bond0
        id: 2121
      mtu: 9000
